# Generated by Django 5.2.3 on 2025-07-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mensagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['data_envio']},
        ),
        migrations.RenameField(
            model_name='mensagem',
            old_name='timestamp',
            new_name='data_envio',
        ),
    ]
